const app=document.getElementById('app');
app.innerHTML=`<div class="wrap"><h1>권혜미 강사 출강 업로드</h1><p class="sub">사진과 핵심 내용만 올리면 블로그 원고가 자동 작성되고 Google Drive에 저장됩니다. 완료되면 이메일로 알려드립니다.</p><div class="card"><form id="f"><label>교육일 <b>*</b></label><input id="lecture_date" type="date" required><label>기관명 <b>*</b></label><input id="institution" placeholder="예: 경남대학교" required><label>교육대상 <b>*</b></label><input id="audience" placeholder="예: 교직원 25명" required><label>교육장소 <b>*</b></label><input id="location" placeholder="예: 부산 영도 라발스 호텔" required><label>강의명 또는 주제 <b>*</b></label><input id="lecture_title" placeholder="예: 차이나는 소통역량강화교육" required><label>간단한 설명 / 꼭 넣을 내용</label><textarea id="highlights" placeholder="예: 협업게임 진행, 팀별 의견공유, 담당자 반응 좋았음"></textarea><label>강의 사진 <b>*</b></label><input id="photos" type="file" accept="image/*" multiple required><small>여러 장 선택 가능 · 전송 전에 자동 압축됩니다.</small><div id="previews" class="previews"></div><button id="send" type="submit">사진 올리고 자동작성 시작</button><div id="status" class="status"></div></form></div></div>`;
const WEBHOOK='https://hook.us2.make.com/essshtdjfumwj3bqtbi4b9wrb3dcwxl3';
const $=id=>document.getElementById(id), today=new Date();
$('lecture_date').value=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
$('photos').addEventListener('change',()=>{const box=$('previews');box.innerHTML='';[...$('photos').files].slice(0,12).forEach(f=>{const img=document.createElement('img');img.src=URL.createObjectURL(f);box.appendChild(img)})});
function blobToBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob)})}
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=URL.createObjectURL(file)})}
async function compressImage(file){if(!file.type.startsWith('image/')) return file;const img=await loadImage(file);const max=1280;let w=img.naturalWidth,h=img.naturalHeight;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let q=.76,blob=await new Promise(r=>c.toBlob(r,'image/jpeg',q));while(blob&&blob.size>230000&&q>.38){q-=.08;blob=await new Promise(r=>c.toBlob(r,'image/jpeg',q))}return blob||file}
$('f').addEventListener('submit',async e=>{e.preventDefault();const btn=$('send'),st=$('status'),files=[...$('photos').files];if(!files.length)return;btn.disabled=true;btn.textContent='사진 압축 및 업로드 중...';st.className='status';st.textContent='';try{if(files.length>12)throw new Error('사진은 최대 12장까지 선택해주세요.');const photoData=[];let n=1;for(const f of files){const compressed=await compressImage(f);photoData.push({order:n++,name:(f.name.replace(/\.[^.]+$/,'')||'photo')+'.jpg',type:'image/jpeg',data:await blobToBase64(compressed)})}const payload={source:'hyemi_upload_web',lecturer:'권혜미',lecture_date:$('lecture_date').value,institution:$('institution').value.trim(),audience:$('audience').value.trim(),location:$('location').value.trim(),lecture_title:$('lecture_title').value.trim(),highlights:$('highlights').value.trim(),photos:photoData};const r=await fetch(WEBHOOK,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('서버 응답 '+r.status);st.className='status ok';st.textContent='전송 완료. 블로그 글 작성이 시작되었습니다. 완료되면 이메일로 알려드립니다.';}catch(err){st.className='status err';st.textContent='전송에 실패했습니다: '+err.message;}finally{btn.disabled=false;btn.textContent='사진 올리고 자동작성 시작';}});